package pojo;
// Generated Mar 21, 2024, 7:46:33 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
public class Product implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	@ManyToOne
	@JoinColumn(name = "category_id")
	private Category category;
	private String name;
	private String description;
	private double price;
	private String manufacturer;
	private String image;
	@Column(name = "created_date")
	private Date createdDate;
	private Boolean active;
	
	@OneToMany(mappedBy = "product")
	private Set<OrderDetail> orderDetails ;
	
	@ManyToMany
	@JoinTable(name = "prod_tag",
			   joinColumns = {@JoinColumn(name = "product_id")},
			   inverseJoinColumns = {@JoinColumn(name = "tag_id")})
	private Set<Tag> tags;
	
	

	@OneToMany(mappedBy = "product")
	private Set<Comment> comments;

	public Product() {
	}

	public Product(Category category, String name) {
		this.category = category;
		this.name = name;
	}

	public Product(Category category, String name, String description, Double price, String manufacturer, String image,
			Date createdDate, Boolean active, Set orderDetails, Set prodTags, Set comments) {
		this.category = category;
		this.name = name;
		this.description = description;
		this.price = price;
		this.manufacturer = manufacturer;
		this.image = image;
		this.createdDate = createdDate;
		this.active = active;
//		this.orderDetails = orderDetails;
//		this.prodTags = prodTags;
//		this.comments = comments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

//	public Set getOrderDetails() {
//		return this.orderDetails;
//	}
//
//	public void setOrderDetails(Set orderDetails) {
//		this.orderDetails = orderDetails;
//	}
//
//	public Set getProdTags() {
//		return this.prodTags;
//	}
//
//	public void setProdTags(Set prodTags) {
//		this.prodTags = prodTags;
//	}
//
//	public Set getComments() {
//		return this.comments;
//	}
//
//	public void setComments(Set comments) {
//		this.comments = comments;
//	}

}
