package pojo;
// Generated Mar 21, 2024, 7:46:33 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SaleOrder generated by hbm2java
 */
@Entity
@Table(name = "sale_order")
public class SaleOrder implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	@ManyToOne
	@JoinColumn(name = "user_id")
	private User user;
	private Date createdDate;
	
	@OneToMany(mappedBy = "saleOrder")
	private Set<OrderDetail> orderDetails;

	public SaleOrder() {
	}

	public SaleOrder(Date createdDate) {
		this.createdDate = createdDate;
	}

	public SaleOrder(User user, Date createdDate, Set orderDetails) {
		this.user = user;
		this.createdDate = createdDate;
		this.orderDetails = orderDetails;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Set getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set orderDetails) {
		this.orderDetails = orderDetails;
	}

}
