package pojo;
// Generated Mar 21, 2024, 7:46:33 PM by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name = "tag")
public class Tag implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	private String name;
	private String tagcol;
	
	@ManyToMany(mappedBy = "tags")
	private Set<Product> products;

	public Tag() {
	}

	public Tag(String name) {
		this.name = name;
	}

	public Tag(String name, String tagcol, Set prodTags) {
		this.name = name;
		this.tagcol = tagcol;
		this.products = prodTags;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTagcol() {
		return this.tagcol;
	}

	public void setTagcol(String tagcol) {
		this.tagcol = tagcol;
	}

	public Set getProdTags() {
		return this.products;
	}

	public void setProdTags(Set prodTags) {
		this.products = prodTags;
	}

}
